import type { DocComment } from '../docs/comments/demoComments';

/** 薅羊毛项目评论（program id 与 referralDeals 一致） */
export const DEMO_DEAL_COMMENTS: DocComment[] = [
  {
    id: 'd-kalshi-1',
    dealId: 'kalshi',
    userId: 'u-jordan-2023',
    body: 'KYC 用护照大概 10 分钟通过；预测 $25 我是分三笔小单做的，成交量按成交价算不是按盈亏。',
    programYear: '2023',
    workState: 'FL',
    workWeek: 'SWT 经验',
    helpfulCount: 21,
    dislikeCount: 1,
    createdAt: '2026-02-10',
  },
  {
    id: 'd-kalshi-1-r1',
    dealId: 'kalshi',
    parentId: 'd-kalshi-1',
    userId: 'u-min-2025',
    body: '加密那 $50 我一开始在错误的市场里刷，不计入；要看官方说明里 eligible markets 列表。',
    programYear: '2025',
    workState: 'TX',
    workWeek: 'Peak',
    helpfulCount: 11,
    dislikeCount: 0,
    createdAt: '2026-02-11',
  },
  {
    id: 'd-kalshi-2',
    dealId: 'kalshi',
    userId: 'u-park-2024',
    body: '本站返现是管理员人工确认，我完成官方条件后留言给站长，大概 3 天到账文案里的保底部分。',
    programYear: '2024',
    workState: 'NY',
    helpfulCount: 8,
    dislikeCount: 0,
    createdAt: '2026-02-15',
  },
  {
    id: 'd-chime-1',
    dealId: 'chime',
    userId: 'u-maya-2025',
    body: 'Direct deposit 我用的雇主 payroll，第二笔 $200 在第三个 pay cycle 才显示 eligible，别太早关户。',
    programYear: '2025',
    workState: 'NJ',
    helpfulCount: 16,
    dislikeCount: 0,
    createdAt: '2025-08-20',
  },
  {
    id: 'd-chime-1-r1',
    dealId: 'chime',
    parentId: 'd-chime-1',
    userId: 'u-alex-2024',
    body: '同意，Chime 对 DD 来源很挑，Zelle 自己转自己有时不算。',
    programYear: '2024',
    workState: 'WI',
    helpfulCount: 7,
    dislikeCount: 1,
    createdAt: '2025-08-22',
  },
  {
    id: 'd-sofi-1',
    dealId: 'sofi',
    userId: 'u-sam-2025',
    body: 'SoFi 开户奖励要满足 direct deposit 门槛，SWT 期间工资进 SoFi 最稳；refer 链接和官网活动不要混用。',
    programYear: '2025',
    workState: 'AK',
    helpfulCount: 12,
    dislikeCount: 0,
    createdAt: '2025-07-01',
  },
  {
    id: 'd-cap1-1',
    dealId: 'capital-one-360',
    userId: 'u-lily-2026',
    body: '360 Performance Savings 促销经常变，以详情页「官方要求」为准；我存 $1000 持满 60 天拿到 bonus。',
    programYear: '2026',
    workState: 'CA',
    helpfulCount: 5,
    dislikeCount: 0,
    createdAt: '2026-01-18',
  },
  {
    id: 'd-bofa-1',
    dealId: 'bofa',
    userId: 'u-jordan-2023',
    body: 'BOA 开户要 branch 或 online 指定 offer code，过期很快；SSN 到手当天 online 申请通过率更高（个人经验）。',
    programYear: '2023',
    workState: 'FL',
    helpfulCount: 9,
    dislikeCount: 0,
    createdAt: '2024-06-10',
  },
  {
    id: 'd-rakuten-1',
    dealId: 'rakuten',
    userId: 'u-maya-2025',
    body: 'Rakuten 返现是季度 check，refer 奖励和购物返现分开看；用 Chrome 插件 + 从 Rakuten 跳转再结账。',
    programYear: '2025',
    workState: 'NJ',
    helpfulCount: 14,
    dislikeCount: 0,
    createdAt: '2025-11-03',
  },
  {
    id: 'd-weee-1',
    dealId: 'weee',
    userId: 'u-min-2025',
    body: '新用户首单免运 + refer 券叠加规则每年变，下单前看 cart 里有没有 applied promotion。',
    programYear: '2025',
    workState: 'TX',
    helpfulCount: 6,
    dislikeCount: 0,
    createdAt: '2025-09-12',
  },
  {
    id: 'd-chase-1',
    dealId: 'chase-secure',
    userId: 'u-park-2024',
    body: 'Secure 卡主要是建信用，bonus 不高但批卡相对友好；deposit 金额=信用额度，离境前记得关或转卡。',
    programYear: '2024',
    workState: 'NY',
    helpfulCount: 10,
    dislikeCount: 0,
    createdAt: '2024-07-25',
  },
];
