export type JourneyPhase = {
  id: string;
  phase: string;
  title: string;
  period: string;
  summary: string;
  tasks: string[];
  docHref: string;
  docLabel: string;
  accent: string;
  glow: string;
};

export const JOURNEY_PHASES: JourneyPhase[] = [
  {
    id: "discover",
    phase: "01",
    title: "了解项目",
    period: "9 月 · 决策期",
    summary: "弄清 SWT 是什么、适合谁、要花多少钱，再决定是否报名。",
    tasks: ["阅读项目概览与常见误区", "评估英语与预算", "对比机构与 Sponsor 资源"],
    docHref: "/docs/intro/eligibility",
    docLabel: "适合人群",
    accent: "#818cf8",
    glow: "rgba(129, 140, 248, 0.45)",
  },
  {
    id: "apply",
    phase: "02",
    title: "报名选岗",
    period: "9–11 月",
    summary: "选定中介、完成英语测试、缴纳定金，正式进入项目流程。",
    tasks: ["对比机构费用与退费政策", "完成机构口语测试", "签订合同并缴纳定金"],
    docHref: "/docs/apply/agency",
    docLabel: "机构与费用",
    accent: "#6366f1",
    glow: "rgba(99, 102, 241, 0.45)",
  },
  {
    id: "interview",
    phase: "03",
    title: "岗位面试",
    period: "11 月–2 月",
    summary: "筛选岗位、参加 Skype/招聘会面试，拿到 Job Offer。",
    tasks: ["研究岗位类型与选岗策略", "准备线上面试工具", "获得雇主 Job Offer"],
    docHref: "/docs/apply/selection",
    docLabel: "选岗指南",
    accent: "#a78bfa",
    glow: "rgba(167, 139, 250, 0.45)",
  },
  {
    id: "ds2019",
    phase: "04",
    title: "文件申请",
    period: "2–4 月",
    summary: "机构提交材料至 Sponsor，等待签发 DS-2019——没有它无法签证和入境。",
    tasks: ["提交完整申请材料", "等待 Sponsor 审核", "签收并妥善保管 DS-2019"],
    docHref: "/docs/visa/visa-materials",
    docLabel: "签证材料",
    accent: "#c084fc",
    glow: "rgba(192, 132, 252, 0.45)",
  },
  {
    id: "visa",
    phase: "05",
    title: "签证面签",
    period: "4–6 月",
    summary: "填写 DS-160、缴费、预约并参加 J-1 面签。",
    tasks: ["填写 DS-160 并缴费", "预约领事馆面签", "携带材料完成英文面试"],
    docHref: "/docs/visa/visa-interview",
    docLabel: "面签流程",
    accent: "#e879f9",
    glow: "rgba(232, 121, 249, 0.45)",
  },
  {
    id: "departure",
    phase: "06",
    title: "行前准备",
    period: "5–6 月",
    summary: "签证通过后再买机票，完成行李、通讯与资金准备。",
    tasks: ["购买机票与补充保险", "整理行李清单", "准备电话卡与现金/银行卡"],
    docHref: "/docs/departure/packing",
    docLabel: "行李清单",
    accent: "#f472b6",
    glow: "rgba(244, 114, 182, 0.45)",
  },
  {
    id: "arrival",
    phase: "07",
    title: "抵美落地",
    period: "6–7 月",
    summary: "入境后按优先级完成 SEVIS 激活、I-94、SSN 与保险核对。",
    tasks: ["激活 SEVIS 并 Monthly Check-in", "下载 I-94", "办理 SSN"],
    docHref: "/docs/arrival/arrival-guide",
    docLabel: "抵美动线",
    accent: "#fb7185",
    glow: "rgba(251, 113, 133, 0.45)",
  },
  {
    id: "living",
    phase: "08",
    title: "在美生活",
    period: "7–9 月",
    summary: "工作、住宿、开销管理，可选第二份工作增加收入。",
    tasks: ["熟悉工作规则与排班", "安顿住宿与日常开支", "了解安全与就医流程"],
    docHref: "/docs/living/work-rules",
    docLabel: "工作规则",
    accent: "#f97316",
    glow: "rgba(249, 115, 22, 0.45)",
  },
  {
    id: "travel",
    phase: "09",
    title: "Grace Period",
    period: "9–10 月",
    summary: "工作结束后 30 天合法停留期，规划美东/美西旅行。",
    tasks: ["确认项目结束日期", "规划旅行路线与预算", "检查保险覆盖范围"],
    docHref: "/docs/return/grace-travel",
    docLabel: "Grace Period 旅行",
    accent: "#fbbf24",
    glow: "rgba(251, 191, 36, 0.45)",
  },
  {
    id: "return",
    phase: "10",
    title: "归国收尾",
    period: "10 月+",
    summary: "税务退税、注销银行账户、整理收支与经历。",
    tasks: ["了解 W-2 与退税流程", "注销美国银行账户", "总结收支与二工/羊毛记录"],
    docHref: "/docs/return/taxes",
    docLabel: "税务与退税",
    accent: "#34d399",
    glow: "rgba(52, 211, 153, 0.45)",
  },
];
