import type { JobRecord } from '../../types/job';

/** 对比页示例岗位（只读展示，不写入 localStorage） */
export const DEMO_SAVED_JOBS: JobRecord[] = [
  {
    jobId: 'DEMO-j-maya-ac',
    jobTitle: 'Server',
    company: 'Atlantic City Boardwalk Grill',
    state: 'NJ',
    city: 'Atlantic City',
    hourlyWage: 12,
    overtimeRate: 1.5,
    tipped: true,
    averageTip: [14, 16],
    avgHoursPerWeek: 42,
    workHoursRange: [38, 45],
    overtimeAvailable: true,
    hasHousing: true,
    housingCostPerWeek: 110,
    housingDistanceKm: 1.2,
    housingCondition: '一般',
    secondJobPossible: '中',
    secondJobHours: 10,
    secondJobIndustry: 'Retail',
    secondJobHourlyWage: 13,
    workStability: 4,
    costOfLivingIndex: 105,
    safetyLevel: 3,
    employerRating: 4,
    lastYearIncidents: false,
    culture: '国际化',
    employerAttitude: '友好',
    description: '旺季 Boardwalk 餐饮，小费稳定；宿舍步行 15 分钟，周末班次多。',
    projectStartDate: '2026-06-01',
    projectEndDate: '2026-09-10',
    verifiedCount: 6,
  },
  {
    jobId: 'DEMO-j-alex-wi',
    jobTitle: 'Housekeeping',
    company: 'Wisconsin Dells Resort',
    state: 'WI',
    city: 'Wisconsin Dells',
    hourlyWage: 11.5,
    overtimeRate: 1.5,
    tipped: false,
    avgHoursPerWeek: 38,
    workHoursRange: [35, 42],
    overtimeAvailable: false,
    hasHousing: true,
    housingCostPerWeek: 95,
    housingDistanceKm: 0.5,
    housingCondition: '良好',
    secondJobPossible: '高',
    secondJobHours: 14,
    secondJobIndustry: 'Convenience Store',
    secondJobHourlyWage: 12.5,
    workStability: 5,
    costOfLivingIndex: 88,
    safetyLevel: 4,
    employerRating: 4,
    lastYearIncidents: false,
    culture: '友好',
    employerAttitude: '非常友好',
    description: '度假村客房岗，工时相对规律；二工便利店晚班常见，净收入靠二工拉高。',
    projectStartDate: '2026-05-20',
    projectEndDate: '2026-09-05',
    verifiedCount: 4,
  },
  {
    jobId: 'DEMO-j-sam-ak',
    jobTitle: 'Lifeguard',
    company: 'Alaska Water Park',
    state: 'AK',
    city: 'Anchorage area',
    hourlyWage: 14,
    overtimeRate: 1.5,
    tipped: false,
    avgHoursPerWeek: 36,
    workHoursRange: [32, 40],
    overtimeAvailable: true,
    hasHousing: true,
    housingCostPerWeek: 130,
    housingDistanceKm: 3,
    housingCondition: '良好',
    secondJobPossible: '低',
    secondJobHours: 0,
    secondJobIndustry: '',
    workStability: 4,
    costOfLivingIndex: 118,
    safetyLevel: 5,
    employerRating: 5,
    lastYearIncidents: false,
    culture: '国际化',
    employerAttitude: '友好',
    description: '救生员需 Red Cross 证；工时不如餐饮岗满，但时薪与工作环境口碑好。',
    projectStartDate: '2026-06-15',
    projectEndDate: '2026-09-20',
    verifiedCount: 3,
  },
];

export function isDemoJobId(jobId: string): boolean {
  return jobId.startsWith('DEMO-');
}
